### PR TITLE
save plotting data to netcdf files

### PR DESCRIPTION
**Pull request by hsiangheleellnl**
I created a flag ```ncfile_save``` in the .cfg run script to save plot data in NetCDF format.

### CODE REVIEW

**Comment by tangq** [comment]
@hsiangheleellnl , have you tested if all figures can be reproduced by these saved files?

**Comment by hsiangheleellnl** [comment]
@tangq The data I saved might not be able to be used for plotting directly. For example, [the NOx aircraft emission plot ](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.lee1061/20230425.amip.e99b02.FourthSmoke_chem_corrected.chrysalis/e3sm_chem_diags_2013_2013/plots/nox_emis_plot.png) has 1-D horizontal mean and 2-D column integrated. So, I save 3-D data instead. The user needs to process the data to reproduce the figures and has more flexibility to use the data. 

Do we actually need to save the 1-D and 2-D arrays?

**Comment by tangq** [comment]
The purpose is to save the plotting data, although it is okay to save some extra data. In this case, I suggest you save the 1D and 2D variables besides the 3D data. Otherwise, it makes it harder to reuse these saved files when rerunning chemdyg.

**Comment by hsiangheleellnl** [comment]
Okay. I will modify the scripts based on your suggestion. Thanks.

**Comment by hsiangheleellnl** [comment]
@tangq The plotting data(final format) have been saved in the netcdf format. The user can reproduce ChemDyg figures from those nc files instead of E3SM outputs.

**Review by tangq — APPROVED** [review]

**Pull request merged**
