### PR TITLE
Revise O3 hole plot x-axis, summary table, and surf. CO & O3 plots

### PR DESCRIPTION
**Pull request by hsiangheleellnl**
fix O3 hole x-axis and remove O3 emission on summary table

### CODE REVIEW

**Comment by hsiangheleellnl** [comment]
@xylar ChemDyg has some changes. Will it be too late for the new E3SM unified?

**Comment by xylar** [comment]
@hsiangheleellnl, no, it's definitely not.  You can make a new release when you like and we can use that.  The conda-forge recipe hasn't been reviewed yet so we're also still waiting on that.

**Comment by tangq** [comment]
@hsiangheleellnl , can you post the ChemDyg test link, so I can see the updated figures and table? Thanks.

**Comment by hsiangheleellnl** [comment]
@tangq The new ozone hole plot is like [this](https://web.lcrc.anl.gov/public/e3sm/diagnostic_output/ac.lee1061/chem_diags/to3areas_O3hole.png). I did not rerun the summary table. It is simplely to remove the line of O3 emission from the table.

**Review by tangq — APPROVED** [review]
Can you update the PR title and descriptions to reflect the actual changes done here? I listed below the changes I saw. It is always a good idea to keep the PR title/description consistent with the changes committed. I am approving this one, but we should avoid doing this.

- Ozone hole figure
- Summary table
- Surface CO and Ozone plots

**Pull request merged**
